#!/usr/bin/env node
const out = require('../src/writer-factory')({ wrap: 80 })

out
.h1('Soft and hard returns')
(`A soft return or soft wrap is the break resulting from line wrap or word wrap (whether automatic or manual), whereas a hard return or hard wrap is an intentional break, creating a new paragraph. With a hard return, paragraph-break formatting can (and should) be applied (either [[Indentation (typesetting)|indenting]] or vertical whitespace). Soft wrapping allows line lengths to adjust automatically with adjustments to the width of the user's window or margin settings, and is a standard feature of all modern text editors, word processors, and [[email client]]s.  Manual soft breaks are unnecessary when word wrap is done automatically, so hitting the "Enter" key usually produces a hard return.`)
(`Alternatively, "soft return" can mean an intentional, stored line break that is not a paragraph break. For example, it is common to print postal addresses in a multiple-line format, but the several lines are understood to be a single paragraph.  Line breaks are needed to divide the words of the address into lines of the appropriate length.`)
(`In the contemporary [[graphical user interface|graphical]] word processors [[Microsoft Word]] and [[OpenOffice.org]], users are expected to type a carriage return ({{Key press|[[Enter key|Enter]]}}) between each paragraph. Formatting settings, such as first-line indentation or spacing between paragraphs, take effect where the carriage return marks the break. A non-paragraph line break, which is a soft return, is inserted using {{Key press|[[shift key|Shift]]|[[Enter key|Enter]]}} or via the menus, and is provided for cases when the text should start on a new line but none of the other side effects of starting a new paragraph are desired.`)
(`In text-oriented markup languages, a soft return is typically offered as a markup tag. For example, in [[HTML]] there is a &lt;br&gt; tag that has the same purpose as the soft return in word processors described above.`)
.nl(2)
.sep()
.h2('Unicode')
.w(`The [[Unicode]] Line Breaking Algorithm determines a set of positions, known as ''break opportunities'', that are appropriate places in which to begin a new line.`)
.w(`The actual line break positions are picked from among the break opportunities by the higher level software that calls the algorithm, not by the algorithm itself, `)
.w(`because only the higher level software knows about the width of the display the text is displayed on and the width of the glyphs that make up the displayed text.`)
.w(`<ref name=annex14>{{cite journal|editor1-last=Heninger|editor1-first=Andy|title=Unicode Line Breaking Algorithm|journal=Technical Reports|date=2013-01-25|volume=Annex #14|issue=Proposed Update Unicode Standard|page=2|url=https://www.unicode.org/L2/L2013/13022-uax14-31.pdf|accessdate=10 March 2015|format=PDF|quote=WORD JOINER should be used if the intent is to merely prevent a line break}}</ref>`)
.nl(2)
(`The Unicode character set provides a line separator character as well as a paragraph separator to represent the semantics of the soft return and hard return.`)
()
(`:0x2028 LINE SEPARATOR `)
(`:         * may be used to represent this semantic unambiguously`)
(`:0x2029 PARAGRAPH SEPARATOR`)
(`:         * may be used to represent this semantic unambiguously`)
()
(`==Word boundaries, hyphenation, and hard spaces==`)
(`<!-- this section could probably use some example illustrations of text before and after wrapping.  Maybe pull from /RTF Pocket Guide/ -->`)
(`The soft returns are usually placed after the ends of complete words, or after the punctuation that follows complete words. However, word wrap may also occur following a [[hyphen]] inside of a word.  This is sometimes not desired, and can be blocked by using a [[non-breaking hyphen]], or [[hard hyphen]], instead of a regular hyphen.`)
()
(`A word without hyphens can be made wrappable by having [[soft hyphen]]s in it.  When the word isn't wrapped (i.e., isn't broken across lines), the soft hyphen isn't visible.  But if the word is wrapped across lines, this is done at the soft hyphen, at which point it is shown as a visible hyphen on the top line where the word is broken.  (In the rare case of a word that is meant to be wrappable by breaking it across lines but ''without'' making a hyphen ever appear, a [[zero-width space]] is put at the permitted breaking point(s) in the word.)<!-- example? a URL maybe? those are so long that they often need breaking, but must never have a hyphen introduced into them. -->`)
()
(`Sometimes word wrap is undesirable between adjacent words.  In such cases, word wrap can usually be blocked by using a '''hard space''' or '''[[non-breaking space]]''' between the words, instead of regular spaces.`)
